name: WebDeployment

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew :webApp:jsBrowserProductionWebpack

      - name: Move Output to Directory
        run: |
          mkdir distribution
          mv -r webApp/build/distributions distribution/

      # Commit and push the directory to a specified branch (e.g., "output-branch")
      - name: Commit and Push to Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add distribution/
          git commit -m "Add output from build"
          git push origin HEAD:deploy-branch