name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI:

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew :webApp:jsBrowserProductionWebpack
      - name: Upload Build Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: my-app-artifact
          path: desktopApp/build/libs/my-app.jar
